import type { Language } from "@/app/components/language-provider";
import type { ReportStatus } from "@/lib/reports/types";

export const reportsCopy = {
  fa: {
    management: "مدیریت محتوا",
    title: "گزارش درخواست‌های محتوا",
    subtitle: "فهرست درخواست‌ها را جستجو، فیلتر و مرتب‌سازی کنید.",
    newRequest: "درخواست جدید",
    loadError: "دریافت گزارش‌ها با خطا مواجه شد.",
    retry: "تلاش دوباره",
    searchLabel: "جستجو در تمام گزارش‌ها",
    searchPlaceholder: "جستجو در تمام ستون‌ها...",
    registeredRequests: "درخواست ثبت‌شده",
    row: "ردیف",
    requestNumber: "شماره درخواست",
    requester: "درخواست کننده",
    createdAt: "تاریخ ثبت",
    subject: "عنوان محتوا",
    description: "شرح محتوا",
    showDate: "تاریخ نمایش",
    showTime: "زمان نمایش",
    showPlace: "محل نمایش",
    status: "وضعیت درخواست",
    operations: "عملیات",
    history: "نمایش سوابق",
    historyTitle: "نمایش سوابق ویرایش",
    edit: "ویرایش",
    statusHistory: "تاریخچه وضعیت",
    statusHistoryTitle: "تاریخچه تغییر وضعیت",
    delete: "حذف",
    request: "درخواست شماره",
    more: "بیشتر",
    less: "کمتر",
    statusFilter: "فیلتر وضعیت درخواست",
    all: "همه موارد",
    from: "از",
    to: "تا",
    chooseDate: "انتخاب تاریخ",
    clear: "پاک کردن",
    clearDateRange: "پاک کردن بازه تاریخ",
    clearDate: "پاک کردن تاریخ",
    statusLabels: {
      initial: "ثبت اولیه",
      review: "درحال بررسی",
      producing: "در حال تولید محتوا",
      produced: "محتوا تولید شد",
      approved: "کل محتوا تایید شد",
      uploaded: "بارگذاری شد",
      checked: "محتوای بارگذاری شده چک شد",
    } satisfies Record<ReportStatus, string>,
  },
  en: {
    management: "Content management",
    title: "Content request reports",
    subtitle: "Search, filter, and sort all content requests.",
    newRequest: "New request",
    loadError: "Unable to load reports.",
    retry: "Try again",
    searchLabel: "Search all reports",
    searchPlaceholder: "Search all columns...",
    registeredRequests: "registered requests",
    row: "Row",
    requestNumber: "Request number",
    requester: "Requester",
    createdAt: "Created at",
    subject: "Content title",
    description: "Description",
    showDate: "Display date",
    showTime: "Display time",
    showPlace: "Display location",
    status: "Request status",
    operations: "Actions",
    history: "View history",
    historyTitle: "View edit history",
    edit: "Edit",
    statusHistory: "Status history",
    statusHistoryTitle: "View status history",
    delete: "Delete",
    request: "request number",
    more: "Show more",
    less: "Show less",
    statusFilter: "Filter request status",
    all: "All items",
    from: "From",
    to: "To",
    chooseDate: "Choose date",
    clear: "Clear",
    clearDateRange: "Clear date range",
    clearDate: "Clear date",
    statusLabels: {
      initial: "Initial",
      review: "Under review",
      producing: "Producing content",
      produced: "Content produced",
      approved: "Content approved",
      uploaded: "Uploaded",
      checked: "Uploaded content checked",
    } satisfies Record<ReportStatus, string>,
  },
} as const;

export type ReportsCopy = (typeof reportsCopy)[Language];

export const gridLocaleText = {
  fa: {
    page: "صفحه",
    more: "بیشتر",
    to: "تا",
    of: "از",
    next: "بعدی",
    last: "آخرین",
    first: "اولین",
    previous: "قبلی",
    loadingOoo: "در حال بارگذاری...",
    noRowsToShow: "داده‌ای برای نمایش وجود ندارد",
    pageSizeSelectorLabel: "تعداد در صفحه:",
    filterOoo: "جستجو...",
    equals: "برابر با",
    inRange: "بین دو تاریخ",
    inRangeStart: "از تاریخ",
    inRangeEnd: "تا تاریخ",
    greaterThanOrEqual: "از تاریخ به بعد",
    lessThanOrEqual: "تا تاریخ",
    notEqual: "نابرابر با",
    contains: "شامل",
    notContains: "شامل نباشد",
    startsWith: "شروع شود با",
    endsWith: "پایان یابد با",
    blank: "خالی",
    notBlank: "خالی نباشد",
    applyFilter: "اعمال",
    resetFilter: "بازنشانی",
    clearFilter: "پاک کردن",
    cancelFilter: "انصراف",
  },
  en: {
    page: "Page",
    more: "More",
    to: "to",
    of: "of",
    next: "Next",
    last: "Last",
    first: "First",
    previous: "Previous",
    loadingOoo: "Loading...",
    noRowsToShow: "No rows to show",
    pageSizeSelectorLabel: "Rows per page:",
    filterOoo: "Search...",
    equals: "Equals",
    inRange: "In range",
    inRangeStart: "From",
    inRangeEnd: "To",
    greaterThanOrEqual: "Greater than or equal",
    lessThanOrEqual: "Less than or equal",
    notEqual: "Not equal",
    contains: "Contains",
    notContains: "Does not contain",
    startsWith: "Starts with",
    endsWith: "Ends with",
    blank: "Blank",
    notBlank: "Not blank",
    applyFilter: "Apply",
    resetFilter: "Reset",
    clearFilter: "Clear",
    cancelFilter: "Cancel",
  },
} as const;
