import type { Language } from "../language-provider";

export const dashboardCopy = {
  fa: {
    welcomeDate: "پنجشنبه، ۲۹ مرداد ۱۴۰۵",
    welcome: "سلام مهدی، روزت بخیر!",
    welcomeText: "این خلاصه‌ای از وضعیت کسب‌وکارت در امروز است.",
    newProject: "ایجاد پروژه جدید",
    options: "گزینه‌های",
    stats: [
      {
        label: "درآمد این ماه",
        value: "۲۴۸ میلیون",
        change: "۱۲٫۵٪",
        note: "نسبت به ماه قبل",
        color: "violet",
      },
      {
        label: "پروژه‌های فعال",
        value: "۱۲",
        change: "۳ پروژه",
        note: "افزوده شده این ماه",
        color: "blue",
      },
      {
        label: "وظایف تکمیل‌شده",
        value: "۸۴٪",
        change: "۸٫۲٪",
        note: "بهبود عملکرد",
        color: "green",
      },
      {
        label: "اعضای تیم",
        value: "۲۸ نفر",
        change: "۲ نفر",
        note: "عضو جدید",
        color: "orange",
      },
    ],
    revenueTitle: "روند درآمد",
    revenueSubtitle: "نمایش درآمد ۶ ماه گذشته",
    revenueValue: "۱٫۲ میلیارد تومان",
    revenueGrowth: "۱۸٫۲٪ رشد",
    ranges: ["۶ ماه اخیر", "۳ ماه اخیر", "امسال"],
    rangeLabel: "بازه زمانی",
    chartLabel: "نمودار روند صعودی درآمد در شش ماه گذشته",
    months: ["اسفند", "فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد"],
    recentActivity: "فعالیت‌های اخیر",
    activitySubtitle: "آخرین تغییرات تیم شما",
    viewAll: "مشاهده همه",
    viewAllActivities: "مشاهده تمام فعالیت‌ها",
    activities: [
      {
        name: "سارا احمدی",
        action: "یک وظیفه را تکمیل کرد",
        target: "طراحی صفحه ورود",
        time: "۱۲ دقیقه پیش",
        color: "#f8b900",
        initials: "سا",
      },
      {
        name: "امیر رضایی",
        action: "فایلی به پروژه افزود",
        target: "راهنمای برند.pdf",
        time: "۴۵ دقیقه پیش",
        color: "#2563eb",
        initials: "ار",
      },
      {
        name: "مهسا کریمی",
        action: "نظر جدیدی ثبت کرد",
        target: "نسخه نهایی داشبورد",
        time: "۲ ساعت پیش",
        color: "#db2777",
        initials: "مک",
      },
    ],
    activeProjects: "پروژه‌های فعال",
    projectsSubtitle: "وضعیت پروژه‌های در حال اجرا",
    allProjects: "همه پروژه‌ها",
    progress: "پیشرفت",
    dueDate: "موعد تحویل",
    projects: [
      {
        name: "طراحی وب‌سایت نوین",
        client: "شرکت آبان",
        progress: 78,
        due: "۲۸ مرداد",
        color: "#f8b900",
        initials: "آن",
      },
      {
        name: "اپلیکیشن همراه‌بانک",
        client: "بانک پارسیان",
        progress: 52,
        due: "۱۰ شهریور",
        color: "#2563eb",
        initials: "پا",
      },
      {
        name: "بازطراحی هویت بصری",
        client: "استودیو دید",
        progress: 91,
        due: "۳ شهریور",
        color: "#059669",
        initials: "دی",
      },
    ],
    morePeople: "+۳",
  },
  en: {
    welcomeDate: "Thursday, August 20, 2026",
    welcome: "Good day, Mehdi!",
    welcomeText: "Here is a summary of your business today.",
    newProject: "Create new project",
    options: "Options for",
    stats: [
      {
        label: "Revenue this month",
        value: "248M",
        change: "12.5%",
        note: "vs. last month",
        color: "violet",
      },
      {
        label: "Active projects",
        value: "12",
        change: "3 projects",
        note: "added this month",
        color: "blue",
      },
      {
        label: "Completed tasks",
        value: "84%",
        change: "8.2%",
        note: "performance increase",
        color: "green",
      },
      {
        label: "Team members",
        value: "28",
        change: "2 people",
        note: "new members",
        color: "orange",
      },
    ],
    revenueTitle: "Revenue trend",
    revenueSubtitle: "Revenue over the past 6 months",
    revenueValue: "IRR 1.2 billion",
    revenueGrowth: "18.2% growth",
    ranges: ["Last 6 months", "Last 3 months", "This year"],
    rangeLabel: "Time range",
    chartLabel: "Upward revenue trend over the past six months",
    months: ["Mar", "Apr", "May", "Jun", "Jul", "Aug"],
    recentActivity: "Recent activity",
    activitySubtitle: "Latest changes from your team",
    viewAll: "View all",
    viewAllActivities: "View all activities",
    activities: [
      {
        name: "Sara Ahmadi",
        action: "completed a task",
        target: "Login page design",
        time: "12 minutes ago",
        color: "#f8b900",
        initials: "SA",
      },
      {
        name: "Amir Rezaei",
        action: "added a project file",
        target: "brand-guide.pdf",
        time: "45 minutes ago",
        color: "#2563eb",
        initials: "AR",
      },
      {
        name: "Mahsa Karimi",
        action: "added a comment",
        target: "Final dashboard",
        time: "2 hours ago",
        color: "#db2777",
        initials: "MK",
      },
    ],
    activeProjects: "Active projects",
    projectsSubtitle: "Status of projects in progress",
    allProjects: "All projects",
    progress: "Progress",
    dueDate: "Due date",
    projects: [
      {
        name: "Novin website design",
        client: "Aban Co.",
        progress: 78,
        due: "Aug 19",
        color: "#f8b900",
        initials: "NO",
      },
      {
        name: "Mobile banking app",
        client: "Parsian Bank",
        progress: 52,
        due: "Sep 1",
        color: "#2563eb",
        initials: "PB",
      },
      {
        name: "Visual identity redesign",
        client: "Did Studio",
        progress: 91,
        due: "Aug 25",
        color: "#059669",
        initials: "DS",
      },
    ],
    morePeople: "+3",
  },
} as const;

export type DashboardCopy = (typeof dashboardCopy)[Language];
export type DashboardStat = DashboardCopy["stats"][number];
